version: '3'

services:
  authentication_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - authentication_network

  authentication_adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - authentication_network

  authentication_service:
    image: authentication_service_image
    build:
      dockerfile: ./Dockerfile
      context: ./authentication
    environment:
      - JWT_SECRET=AckoCar123
    depends_on:
      - authentication_database
    ports:
      - 5000:5000
    networks:
      - authentication_network

  shop_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  shop_adminer:
    image: adminer
    ports:
      - 8081:8080

networks:
  authentication_network: