version: '3'

services:
  authentication_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - authentication_network
    volumes:
      - authentication_database_volume:/var/lib/mysql

  authentication_adminer:
    image: adminer
    ports:
      - 5004:8080
    networks:
      - authentication_network

  authentication_service:
    image: authentication_service_image
    build:
      dockerfile: ./Dockerfile
      context: ./authentication
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=authentication_database
      - MYSQL_DATABASE_NAME=authentication
      - JWT_SECRET=AckoCar123
    depends_on:
      - authentication_database
    ports:
      - 5000:5000
    networks:
      - authentication_network

  shop_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - shop_network
    volumes:
      - shop_database_volume:/var/lib/mysql

  shop_adminer:
    image: adminer
    ports:
      - 5005:8080
    networks:
      - shop_network

  owner_service:
    image: owner_service_image
    build:
      dockerfile: ./owner_service_Dockerfile
      context: ./shop
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=shop_database
      - MYSQL_DATABASE_NAME=shop
      - SPARKY_IP=sparky
      - SPARKY_PORT=5431
      - SPARKY_PRODUCT_STATISTICS=product_statistics
      - SPARKY_CATEGORY_STATISTICS=category_statistics
      - JWT_SECRET=AckoCar123
      - SERVICE=owner
    depends_on:
      - shop_database
    ports:
      - 5001:5001
    networks:
      - shop_network

  customer_service:
    image: customer_service_image
    build:
      dockerfile: ./customer_service_Dockerfile
      context: ./shop
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=shop_database
      - MYSQL_DATABASE_NAME=shop
      - JWT_SECRET=AckoCar123
      - SERVICE=customer
    depends_on:
      - shop_database
      - owner_service
    ports:
      - 5002:5002
    networks:
      - shop_network

  courier_service:
    image: courier_service_image
    build:
      dockerfile: ./courier_service_Dockerfile
      context: ./shop
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=shop_database
      - MYSQL_DATABASE_NAME=shop
      - JWT_SECRET=AckoCar123
      - SERVICE=courier
    depends_on:
      - shop_database
      - owner_service
    ports:
      - 5003:5003
    networks:
      - shop_network

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - shop_network

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shop_network

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shop_network

  spark-history-server:
    image: bde2020/spark-history-server:3.3.0-hadoop3.3
    container_name: spark-history-server
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - /tmp/spark-events-local:/tmp/spark-events
    networks:
      - shop_network

  sparky:
    image: sparky_image
    build:
      dockerfile: ./sparky_Dockerfile
      context: ./
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    environment:
      - PRODUCTION=True
      - ENABLE_INIT_DAEMON=False
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=shop_database
      - MYSQL_DATABASE_NAME=shop
      - JWT_SECRET_KEY=AckoCar123
      - SPARK_SUBMIT_ARGS=--driver-class-path /app/mysql-connector-j-8.0.33.jar --jars /app/mysql-connector-j-8.0.33.jar
    # DMZ - ports:
    #  - 5431:5431
    networks:
      - shop_network

networks:
  authentication_network:
  shop_network:

volumes:
  authentication_database_volume:
  shop_database_volume: